import type { Metadata } from "next";
import {
  Atkinson_Hyperlegible,
  Atkinson_Hyperlegible_Mono,
} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const atkinson = Atkinson_Hyperlegible({
  weight: "400",
  variable: "--font-atkinson",
  subsets: ["latin-ext"],
});

const atkinsonMono = Atkinson_Hyperlegible_Mono({
  variable: "--font-atkinson-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: {
    template: "%s | Vu Huy Nguyen",
    default: "Vu Huy Nguyen",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.variable} ${atkinsonMono.variable} antialiased`}
      >
        <main className="mx-auto max-w-screen-sm px-5">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
